apiVersion: v1
kind: Service
metadata:
  namespace: Staging
  name: redis-master
  labels:
    app: redis
    role: master
    tier: backend
spec:
  type: LoadBalancer
  ports:
  - port: 6379
    targetPort: 6379
  selector:
    app: redis
    role: master
    tier: backend

apiVersion: v1
kind: Service
metadata:
  namespace: Production
  name: redis-master
  labels:
    app: redis
    role: master
    tier: backend
spec:
  type: LoadBalancer
  ports:
  - port: 6378
    targetPort: 6378
  selector:
    app: redis
    role: master
    tier: backend
