apiVersion: v1
kind: Service
metadata:
  namespace: Staging
  name: redis-slave
  labels:
    app: redis
    role: slave
    tier: backend
spec:
  type: LoadBalancer
  ports:
  - port: 6379
  selector:
    app: redis
    role: slave
    tier: backend

apiVersion: v1
kind: Service
metadata:
  namespace: Production
  name: redis-slave
  labels:
    app: redis
    role: slave
    tier: backend
spec:
  type: LoadBalancer
  ports:
  - port: 6378
  selector:
    app: redis
    role: slave
    tier: backend
